apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpservice
  labels:
    app: httpservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpservice
  template:
    metadata:
      labels:
        app: httpservice
    spec:
      containers:
        - name: httpservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" | quote }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.kafkaBootstrap }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.env.datasourceUrl }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.env.datasourceUsername }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.env.datasourcePassword }}"
            - name: SPRING_REDIS_HOST
              value: "{{ .Values.env.redisHost }}"
            - name: SPRING_REDIS_PORT
              value: "{{ .Values.env.redisPort }}"
            - name: REFRESH_SECRET
              value: "{{ .Values.security.refreshSecret }}"
