apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: httpservice-monitor
  labels:
    app: httpservice
    release: prometheus
spec:
  selector:
    matchLabels:
      app: httpservice
  endpoints:
    - port: 8080
      path: /actuator/prometheus
      interval: 30s
