apiVersion: apps/v1
kind: Deployment
metadata:
  name: messegerparody
  labels:
    app: messegerparody
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messegerparody
  template:
    metadata:
      labels:
        app: messegerparody
    spec:
      containers:
        - name: messegerparody
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.kafkaBootstrap }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.env.datasourceUrl }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.env.datasourceUsername }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.env.datasourcePassword }}"
            - name: SPRING_REDIS_HOST
              value: "{{ .Values.env.redisHost }}"
            - name: SPRING_REDIS_PORT
              value: "{{ .Values.env.redisPort }}"
