apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: messegerparody-monitor
  labels:
    app: messegerparody
    release: prometheus
spec:
  selector:
    matchLabels:
      app: messegerparody
  endpoints:
    - port: 8082
      path: /actuator/prometheus
      interval: 30s
