server:
  port: 2016
  address: 0.0.0.0
logging:
  level:
    # Устанавливаем уровень DEBUG для Spring, чтобы видеть максимум информации о старте
    org.springframework.boot: DEBUG
    # Устанавливаем уровень DEBUG для вашего кода, чтобы видеть ваши собственные лог-сообщения
    com.example.springexample: DEBUG

  # Эта настройка выводит имя приложения в лог, что очень удобно, когда у вас несколько сервисов
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{appName:-}] - %msg%n"

spring:
  application:
    name: jwt-validator-service