apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tls-issuer
  namespace: default
spec:
  acme:
    email: dmitrix2009@mail.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tls-secret
    solvers:
      - http01:
          ingress:
            class: nginx
