{{- if .Values.infra.kafka }}
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          ports:
            - containerPort: 9092
          env:
            - name: KRAFT_BROKER_ID
              value: "{{ default "1" .Values.kafka.brokerId }}"
            - name: KRAFT_CONTAINER_HOST_NAME
              value: "{{ default "kafka" .Values.kafka.hostName }}"
            - name: KRAFT_CREATE_TOPICS
              value: "{{ default "" .Values.kafka.createTopics }}"
            - name: KRAFT_PARTITIONS_PER_TOPIC
              value: "{{ default "1" .Values.kafka.partitionsPerTopic }}"
            - name: KRAFT_AUTO_CREATE_TOPICS
              value: "{{ default "true" .Values.kafka.autoCreateTopics }}"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data
          emptyDir: {}
{{- end }}
