{{- if .Values.secrets.private_key_secret_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.private_key_secret_name }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  private_key: |
{{- default "PLACEHOLDER_PRIVATE_KEY" .Values.secrets.private_key | nindent 4 }}
{{- end }}

{{- if .Values.secrets.public_key_secret_name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.public_key_secret_name }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  public_key: |
{{- default "PLACEHOLDER_PUBLIC_KEY" .Values.secrets.public_key | nindent 4 }}
{{- end }}

{{- if .Values.secrets.refresh_secret_name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.refresh_secret_name }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  refresh_secret: {{ default "PLACEHOLDER_REFRESH_SECRET" .Values.secrets.refresh_secret | quote }}
{{- end }}

{{- if .Values.secrets.https_secret_name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.https_secret_name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ default "PLACEHOLDER_TLS_CRT" .Values.secrets.https_secret_crt | b64enc }}
  tls.key: {{ default "PLACEHOLDER_TLS_KEY" .Values.secrets.https_secret_key | b64enc }}
{{- end }}
