debug: true

grpc:
  server:
    port: ${DB_PORT}
  client:
    NotifyService:
      address: "dns:///${GRPC_SERVICE_NAME}.default.svc.cluster.local:${INGRESS_PORT}"
      negotiationType: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 10s
      default-load-balancing-policy: round_robin
      security:
        authority-override: handle.internal


spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_ADRESS}.default.svc.cluster.local
    producer:
      properties:
        max.request.size: 10485760

  datasource:
    url: jdbc:postgresql://${DB_SERVICE}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD
    driver-class-name: org.postgresql.Driver


  r2dbc:
    url: r2dbc:postgresql://${DB_SERVICE}:${DB_PORT}/${DB_NAME}
    username: bot
    password: bot


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.jdbc: DEBUG

    org.springframework.beans.factory: DEBUG
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: DEBUG
    org.hibernate: DEBUG

