; worker_processes 1;
; events {
;     worker_connections 1024;
; }
; http {
;     # --- UPSTREAM'Ы (Группы серверов) ---
;     # Upstream для твоего Java-сервиса-валидатора
;     upstream auth_service {
;         server host.docker.internal:2010;
;     }
;     upstream jwt-validator{
;     server host.docker.internal:2016;
;     }
;
;     # Upstream для  основного микросервиса
;     upstream main {
;         server host.docker.internal:2009;
;     }
;     upstream prometheus {
;         server host.docker.internal:9090;
;     }
;     upstream grafana {
;         server host.docker.internal:3000;
;     }
;
;
;     server {
;         listen 80;
;
;         error_page 419 = @handle_refresh_flow;
;         location = /prometheus/ {
;             proxy_pass http://prometheus;
;         }
;          location = /grafana/ {
;                     proxy_pass http://grafana;
;                 }
;         location = /auth {
;             internal;
;             proxy_pass http://jwt-validator/jwtcheck;
;             proxy_pass_request_body off;
;             proxy_set_header Content-Length "";
;             proxy_set_header Cookie "";
;             proxy_set_header X-Original-URI $request_uri;
;             proxy_set_header Authorization "Bearer $cookie_access";
;         }
;
;         # --- ПУБЛИЧНЫЕ ИСКЛЮЧЕНИЯ (БЕЗ ПРОВЕРКИ JWT) ---
;         # Все эти location'ы используют одинаковые настройки из файла
;         location = /welcome { include common_proxy_settings.conf; }
;         location = /startauth {
;             proxy_pass http://auth_service;
;             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;
;
;         }
;         location = /reactive/register { include common_proxy_settings.conf; }
;         location = /authcallback { include common_proxy_settings.conf; }
;         location = /reactive/login { include common_proxy_settings.conf; }
;         location = /collect-fingerprint { include common_proxy_settings.conf; }
;         location = /exchangeTokens { include common_proxy_settings.conf; }
;
;
;         # --- ГЛАВНОЕ ПРАВИЛО "ПО УМОЛЧАНИЮ" (С ПРОВЕРКОЙ JWT) ---
;         # Это правило сработает для всех остальных запросов
;         location / {
;             # ЗАПУСКАЕМ ПРОВЕРКУ JWT
;             auth_request /auth;
;             auth_request_set $auth_user_id $upstream_http_x_user_id;
;             proxy_set_header X-User-ID $auth_user_id;
;             proxy_pass http://main ;
;             proxy_set_header Host $host;
;             proxy_set_header X-Real-IP $remote_addr;
;             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;         }
;         location @handle_refresh_flow {
;               # Эта функция берет строку и кодирует ее так, чтобы она безопасно передавалась как параметр URL
;               #$original_uri_encoded: Это наша целевая переменная, куда будет записан закодированный URI.
;               # $request_uri$is_args$args: Это конкатенация (объединение) трех встроенных NGINX переменных:
;                #$request_uri: Полный исходный URI запроса (например, /api/users?id=123).
;                #$is_args: Эта переменная содержит ?, если в URI есть аргументы, и пуста, если аргументов нет. Она нужна, чтобы гарантировать правильное добавление ? перед параметрами.
;                #$args: Эта переменная содержит только часть URI после ? (то есть, сами параметры запроса, например, id=123).
;                 #set $original_uri_encoded "";
;                 #if ($request_uri) {
;                  #   set_escape_uri $original_uri_encoded $request_uri$is_args$args;
;                 #}
;                 return 302 /collect-fingerprint?return_url=$request_uri;
;             }
;     }
; }