apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.kafkaBootstrap }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.env.datasourceUrl }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.env.datasourceUsername }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.env.datasourcePassword }}"
            - name: SPRING_REDIS_HOST
              value: "{{ .Values.env.redisHost }}"
            - name: SPRING_REDIS_PORT
              value: "{{ .Values.env.redisPort }}"
            - name: GOOGLE_CLIENT_ID
              value: "{{ .Values.google.clientId }}"
            - name: GOOGLE_CLIENT_SECRET
              value: "{{ .Values.google.clientSecret }}"
