apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwtproxy
  labels:
    app: jwtproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwtproxy
  template:
    metadata:
      labels:
        app: jwtproxy
    spec:
      containers:
        - name: jwtproxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.kafkaBootstrap }}"
