
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - services-network
    volumes:
      - ./redis:/data
    restart: unless-stopped
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka_messenger
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_PROCESS_ROLES=broker,controller
      - CLUSTER_ID=1
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9099,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9099
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_MAX_REQUEST_SIZE=10485760
      - KAFKA_MESSAGE_MAX_BYTES=10485760
      - KAFKA_REPLICA_FETCH_MAX_BYTES=11534336
      - KAFKA_FETCH_MAX_BYTES=11534336

    ports:
      - "9099:9099"  # для клиента
      - "9093:9093"  # для контроллера
    networks:
      - services-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9096:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      прокидывается конфиг для прометея через том
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 9094:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always
networks:
  services-network:
    driver: bridge
volumes:
  redis:
    driver: local