apiVersion: v2
name: hybrid
description: Umbrella chart for Hybrid Platform (minimal)
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: authservice
    version: 0.1.0
    condition: authservice.enabled
  - name: httpservice
    version: 0.1.0
    condition: httpservice.enabled
  - name: jwtproxy
    version: 0.1.0
    condition: jwtproxy.enabled
  - name: messegerparody
    version: 0.1.0
    condition: messegerparody.enabled
