# Порта для сервисов
ports:
  main_port: 8080
  auth_port: 8081
  handle_port: 8082
  db_port: 8083
  proxy_port: 8084

# Включение/выключение сервисов
authservice:
  enabled: true
httpservice:
  enabled: true
jwtproxy:
  enabled: true
messegerparody:
  enabled: true
handleservice:
  enabled: true

# Kafka настройки
kafka:
  enabled: true
  bootstrap_servers: kafka:9092

# Prometheus настройки
monitoring:
  enabled: true
  prometheus_port: 9090
  grafana_port: 3000

# База данных
database:
  host: postgres
  port: 5432
  name: hybrid_db

# Redis
redis:
  host: redis-master
  port: 6379

# Секреты
secrets:
  private_key_secret_name: "private-key-secret"
  public_key_secret_name: "public-key-secret"
  refresh_secret_name: "refresh-secret"
  https_secret_name: "https-secret"
  private_key: "PLACEHOLDER_PRIVATE_KEY"
  public_key: "PLACEHOLDER_PUBLIC_KEY"
  refresh_secret: "PLACEHOLDER_REFRESH_SECRET"
  https_secret_crt: "PLACEHOLDER_TLS_CRT"
  https_secret_key: "PLACEHOLDER_TLS_KEY"